### PR TITLE
CLP-000: Remove release workflow

### PR DESCRIPTION
**Pull request by stefan-scheidewig**
As we use tusd as a library, we remove the release workflow.

### CODE REVIEW

**Comment by wmentzel** [comment]
If we use it as library we can get rid of the fork all together, don't we?

**Comment by stefan-scheidewig** [comment]
> If we use it as library we can get rid of the fork all together, don't we?

unfortunately not yet as we have made some adjustments which didn't land finally in the upstream repo. the maintainer doesn't pass the request context to the hooks but tbh haven't checked the code state for quite some while. momentchen ...

**Comment by stefan-scheidewig** [comment]
> > If we use it as library we can get rid of the fork all together, don't we?
> 
> unfortunately not yet as we have made some adjustments which didn't land finally in the upstream repo. the maintainer doesn't pass the request context to the hooks but tbh haven't checked the code state for quite some while. momentchen ...

no, still that weird behaviour. the maintainer argues that the network connection could drop and all bytes uploaded from the last chunk call could get lost: https://github.com/tus/tusd/pull/740

**Comment by stefan-scheidewig** [comment]
> > > If we use it as library we can get rid of the fork all together, don't we?
> > 
> > 
> > unfortunately not yet as we have made some adjustments which didn't land finally in the upstream repo. the maintainer doesn't pass the request context to the hooks but tbh haven't checked the code state for quite some while. momentchen ...
> 
> no, still that weird behaviour. the maintainer argues that the network connection could drop and all bytes uploaded from the last chunk call could get lost: [tus#740](https://github.com/tus/tusd/pull/740)

but we can get rid of this repo when we have async video processing in place. the context topic could have been worked around with some ugly hack but more important - and which is actually blocking us from removing our little fork - is [this](https://github.com/tus/tusd/pull/741) one line change pr, which directly writes to the response object. but the maintainer argues that the callback should not block too long. so he dictates how tusd should be used as a library in that regard. but it is free lunch so we don't complain and accept it.

**Comment by wmentzel** [comment]
> > > If we use it as library we can get rid of the fork all together, don't we?
> > 
> > 
> > unfortunately not yet as we have made some adjustments which didn't land finally in the upstream repo. the maintainer doesn't pass the request context to the hooks but tbh haven't checked the code state for quite some while. momentchen ...
> 
> no, still that weird behaviour. the maintainer argues that the network connection could drop and all bytes uploaded from the last chunk call could get lost: [tus#740](https://github.com/tus/tusd/pull/740)

but then we need the release action. Otherwise we cannot release with the change we made.

**Comment by stefan-scheidewig** [comment]
> but then we need the release action. Otherwise we cannot release with the change we made.

the release action creates a docker image. for golang you just need that github repo ...

**Comment by wmentzel** [comment]
> > but then we need the release action. Otherwise we cannot release with the change we made.
> 
> the release action creates a docker image. for golang you just need that github repo ...

Ah ok, got it! :+1:

**Review by wmentzel — APPROVED** [review]

**Review by andis1996 — APPROVED** [review]

**Pull request merged**
